repos:
    -  repo: https://github.com/antonbabenko/pre-commit-terraform
       rev:  v1.88.0
       hooks:
           -  id: terraform_fmt
           -  id:  terraform_validate

    -  repo: https://github.com/adrienverge/yamllint
       rev:  v1.35.1
       hooks:
           -  id: yamllint

    - repo:  https://github.com/ansible/ansible-lint
       rev:  v24.2.0
       hooks:
           - id:  ansible-lint
