name:  Terraform  CI

on:
   pull_request:
       paths:
           - "terraform/**"
    push:
       branches:  [ main  ]
       paths:
           -  "terraform/**"

jobs:
    terraform:
       runs-on: ubuntu-latest

       steps:
           -  name: Checkout
               uses: actions/checkout@v4

           -  name: Set  up  Terraform
              uses:  hashicorp/setup-terraform@v3
              with:
                  terraform_version:  1.6.0

          -  name:  Terraform  fmt
              run:  terraform fmt  -check  -recursive
              working-directory:  terraform

          -  name:  Terraform  validate
              run:  terraform  validate
              working-directory:  terraform/networking
